package Goodnight::Map::Area;

use warnings;
use strict;

use Class::Constant
    NOTHING   => "Nothing",
    LOTHORIL  => "Lothoril",
    GLOOM     => "Gloom",
    MOON      => "Moon",
    MIRROW    => "Mirrow",
    GLORIM    => "Glorim",
    KORKITH   => "Korkith",
    LOST      => "the Lost",
    DEAD      => "Dead",
    WEIRD     => "Weird",
    UGRAK     => "Ugrak",
    DEATH     => "Death",
    DOOM      => "Doom",
    DESPAIR   => "Despair",
    VORGATH   => "Vorgath",
    USHGARAK  => "Ushgarak",
    UGRORN    => "Ugrorn",
    KOR       => "Kor",
    TOOMOG    => "Toomog",
    OGRIM     => "Ogrim",
    DODRAK    => "Dodrak",
    GORGRATH  => "Gorgrath",
    VALETHOR  => "Valethor",
    COROTH    => "Coroth",
    ASHIMAR   => "Ashimar",
    ITHRIL    => "Ithril",
    SHADOWS   => "Shadows",
    BLOOD     => "Blood",
    THRALL    => "Thrall",
    TORKREN   => "Torkren",
    GARD      => "Gard",
    MITHARG   => "Mitharg",
    MOON2     => "the Moon",
    ISERATH   => "Iserath",
    SHIMERIL  => "Shimeril",
    ODRARK    => "Odrark",
    ISHMALAY  => "Ishmalay",
    BRITH     => "Brith",
    SILENCE   => "Silence",
    ELENIL    => "Elenil",
    RORATH    => "Rorath",
    MORNING   => "Morning",
    THIMRATH  => "Thimrath",
    CORELAY   => "Corelay",
    RATHORN   => "Rathorn",
    LORGRIM   => "Lorgrim",
    LOR       => "Lor",
    FADRATH   => "Fadrath",
    DROON     => "Droon",
    GRARG     => "Grarg",
    DREAMS    => "Dreams",
    ITHRORN   => "Ithrorn",
    WHISPERS  => "Whispers",
    XAJORKITH => "Xajorkith",
    HERATH    => "Herath",
    KUMAR     => "Kumar",
    MARAKITH  => "Marakith",
    TARG      => "the Targ",
    UTARG     => "Utarg",
    ATHORIL   => "Athoril",
    DREGRIM   => "Dregrim",
    DAWN      => "Dawn",
    TRORN     => "Trorn",
    COOM      => "Coom";

1;
